---
title: "exp1_analysis"
output: html_document
---

```{r libraries}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

library(tidyverse)
library(jsonlite)
library(here)
library(tidyboot)
library(anonymizer)
library(lme4)
library(broom)
library(ggthemes)
library(RColorBrewer)
theme_set(theme_classic(base_size = 18))
```

```{r data}
data <- read_csv(here("data/exp1_turk_data.csv"))

keep_subjs <- data %>%
  filter(searchtype == "colorcheck", chosetarget == TRUE, attncheckscore >= 6) %>%
  group_by(subid) %>%
  count() %>%
  filter(n == 4)

sub_data_gathered <- data %>%
  filter(subid %in% keep_subjs$subid) %>%
  gather(item, chose, chosetarget, choselure, choseunique) %>%
  mutate(item = gsub("chose", "", item),
         subid = as.factor(subid))

sub_data <- data %>%
  filter(subid %in% keep_subjs$subid)

mean_data <- sub_data_gathered %>%
  filter(trialtype != 0) %>%
  group_by(searchtype, adj, condition, item, subid) %>%
  summarise(chose = mean(chose), n = n()) %>%
  tidyboot_mean(chose) %>%
  ungroup() %>%
  mutate(adjective_used = factor(adj, labels = c("noun", "adjective noun")))
```

```{r plots}
ggplot(mean_data %>% filter(searchtype == "uniquetarget", item == "target"), 
       aes(x = condition, color = adjective_used)) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper, y = empirical_stat),
                  position = position_dodge(.5)) + 
  ylab("Item chosen") + 
  xlab("") +
  theme(rect = element_rect(fill = "transparent"))


p1 <- ggplot(mean_data %>% filter(searchtype == "contrast", item != "unique"), 
       aes(x = adjective_used, color = item)) +
    facet_wrap(~ condition) +
    geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper, y = empirical_stat),
                  position = position_dodge(.5)) + 
    ylab("Item chosen") + 
    xlab("")+
    theme(rect = element_rect(fill = "transparent"),
          panel.background = element_rect(fill = "transparent",colour = NA))  +
    scale_colour_manual(values=c("#ff8e2a", "#5c8b14", "#66CC99"))


p1

ggsave(p1, filename = "exp1_p1.png",  bg = "transparent")
```

```{r models}
# in contrast trials w/an adjective, do people choose the target over the lure?
# prereg'd
chance_model <- sub_data %>%
  filter(searchtype == "contrast", adj == TRUE, (chosetarget == TRUE || choselure == TRUE)) %>%
  glmer(chosetarget ~ 1 + (1 | subid),
        family = "binomial", data = .) %>%
  tidy() %>%
  filter(group == "fixed")
chance_model

# in only *color* contrast trials w/an adjective, do people choose the target over the lure?
# not prereg'd
color_model <- sub_data %>%
  filter(searchtype == "contrast", adj == TRUE, condition == "color",
         (chosetarget == TRUE || choselure == TRUE)) %>%
  glmer(chosetarget ~ 1 + (1 | subid),
        family = "binomial", data = .) %>%
  tidy() %>%
  filter(group == "fixed")
color_model

# in contrast trials w/an adjective, 
# does the type of adjective matter in choosing target over lure?
# prereg'd
adj_type_model <- sub_data %>%
  filter(searchtype == "contrast", adj == TRUE, (chosetarget == TRUE | choselure == TRUE)) %>%
  glmer(chosetarget ~ condition + (1 | subid),
        family = "binomial", data = .) %>%
  tidy() %>%
  filter(group == "fixed")

adj_type_model

# in contrast trials, do adj type and presence of an adj interact 
# in determining target over lure choice?
# not prereg'd
adj_by_adjtype_model <- sub_data %>%
  filter(searchtype == "contrast", (chosetarget == TRUE | choselure == TRUE)) %>%
  glmer(chosetarget ~ condition * adj + (1 | subid),
        family = "binomial", data = .) %>%
  tidy() %>%
  filter(group == "fixed")
adj_by_adjtype_model

# throw everything in the model
# prereg'd
full_model <- sub_data %>%
  filter(searchtype == "contrast" | searchtype == "uniquetarget") %>%
  glmer(chosetarget ~ adj * condition * searchtype + (searchtype * adj | subid),
        family = "binomial", data = .) %>%
  tidy() %>%
  filter(group == "fixed")

full_model
```

